### ISSUE TITLE
Could not determine MIME type of '{self.filename}' with tempfile.NamedTemporaryFile

### ISSUE THREAD

**Issue by 57uff3r** [mindee/mindee-api-python#126]
### Prerequisites

Mindee library raises `raise MimeTypeError(f"Could not determine MIME type of '{self.filename}'")` when being used with `tempfile.NamedTemporaryFile`.

```
f = tempfile.NamedTemporaryFile()

# Some TMP file magic happens here

mindee_client = Client(api_key=self.config.MINDEE_API_KEY.get_secret_value())
input_doc = mindee_client.doc_from_bytes(f.read(), f.name)

```

### Description

The problem is caused by the usage of library **mimetypes** which relies on file extensions when trying to guess MIME of file. However, temporary name, available in **NamedTemporaryFile**  doesn't contain the file extension, hence, **mimetypes** can't guess MIME.

### Solution

There are two solutions:

* To create an additional optional argument in `doc_from_bytes()` function accepting MIME types sent there manually.
* To switch to `magic` library, based on **libmagic**. It can guess MIME pretty well using binary signatures of different types of files. It creates extra dependencies for developers since it requires **libmagic** to be installed on the computer.

However, guessing MIME from the file extension is not an optimal way to define correct MIME since sometimes users upload, for example, PNG files with **.jpg** extension and it will cause errors.

**Comment by ianardee** [comment]
I'll look into doing this the proper way, without relying on the extension.

As a quick and dirty workaround, you can do something like `f.name + ".pdf"`.

The server does a in-depth check of the file (without relying on the extension).

In the library we are mainly trying to avoid you the pain of having to wait for the server's response for something that can be easily avoided.

**Comment by 57uff3r** [comment]
Thank you for your response, @ianardee, that's what I've indeed done, but was thinking that sharing this case may help to come up with some new good ideas for Mindee lib ✌️

**Comment by sebastianMindee** [comment]
Since the detection of mime types is notoriously unreliable when only reading a file's content, and since most python mime type libraries rely on the name of the given files, we don't consider this to be an active issue.
That said, anonymous files containing a valid PDF tag should be properly identified when using the `fix_pdf` parameter during input creation (see #190).
