### ISSUE TITLE
Error in http response

### ISSUE THREAD

**Issue by DrRSatzteil** [mindee/mindee-api-python#227]
Hi,

I just got an error like the one below for an api call that I did not see before:

File "/usr/local/lib/python3.12/site-packages/mindee/mindee_http/response_validation.py", line 67, in clean_request_json and response_json["api_request"]["status_code"].isdigit()
AttributeError: 'int' object has no attribute 'isdigit'

This happened after calling a custom API built with the new API builder. Previous calls did not teilen this error. Please let me know if I can provide you more information.

**Comment by sebastianMindee** [comment]
Thank you for mentioning this! A fix has been released in version 4.5.0.
