### ISSUE TITLE
Custom 500

### ISSUE THREAD

**Issue by DrRSatzteil** [mindee/mindee-api-python#230]
Hi,

it's me again. Thank you for fixing the http code error so quickly. Now I can see the actual error from the server but it's not very informative:

File "/usr/local/lib/python3.12/site-packages/mindee/client.py", line 397, in _get_queued_document raise handle_error(mindee.error.mindee_http_error.MindeeHTTPServerError: custom 500 HTTP error: None - None

My code and the api works fine with other documents but not with this particular one. Is there anything I can do to debug this?!

**Comment by sebastianMindee** [comment]
Hello again, 

Unfortunately, this goes beyond what the library's repo issues are for. I recommend you reach out using the intercom button (bottom right) on the [Mindee website](https://www.mindee.com/) to get more personalized support about this. Alternatively, you can post any questions on the [Mindee Community Slack](https://join.slack.com/t/mindee-community/shared_invite/zt-2d0ds7dtz-DPAF81ZqTy20chsYpQBW5g).

Thank you for your understanding
