### ISSUE TITLE
Add a consistent User-Agent header in Python SDK requests

### ISSUE THREAD

**Issue by olivmindee** [mindee/mindee-api-python#30]
The node SDK contains a header `User-Agent` : `mindee-node/${sdkVersion} node/${process.version}` when making the request to Mindee API (api.mindee.net/v1).

We should add the same header so that Mindee API backend has the information.

Example:

`User-Agent` : `mindee-python/v1.3.0 python/3.8.12`

**Comment by ianardee** [comment]
fixed by #36
