### ISSUE TITLE
Adapt help display for no-raise-errors

### ISSUE THREAD

**Issue by fharper** [mindee/mindee-api-python#59]
### Prerequisites

Put an X between the brackets on this line if you have done all of the following:

* [x] Reproduced the problem or exposed a new need
* [x] Checked the github existing issues

### Description

`--no-raise-errors` definition is displayed after a break line probably caused by the fact it's too long.

### Steps to Reproduce

Run `./mindee-cli.sh -h`

**Expected behavior:**

no break line

**Actual behavior:**

<img width="559" alt="CleanShot 2022-02-17 at 17 44 19@2x" src="https://user-images.githubusercontent.com/1170989/154583946-ff1bc9f4-7231-4bc9-9187-c42a3b3a347a.png">

**Reproduces how often:**

Always

### Versions

2.0.1

**Comment by ianardee** [comment]
Yes this is the normal behavior for the `argsparse` built-in module.

There are ways of customizing the output, but this requires writing a custom class.

Frankly the work/benefit ratio makes this very low priority for me.
The CLI is just a nice to have, not core to the developer experience.
